/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as BookmarksIndexRouteImport } from './routes/bookmarks/index'
import { Route as BookmarksIdRouteImport } from './routes/bookmarks/$id'
import { Route as BookmarksArchiveRouteImport } from './routes/bookmarks/archive'
import { Route as BookmarksFavoritesRouteImport } from './routes/bookmarks/favorites'
import { Route as RssIndexRouteImport } from './routes/rss/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsSectionRouteImport } from './routes/settings/$section'
import { Route as RssArticleIdRouteImport } from './routes/rss/article.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksIndexRoute = BookmarksIndexRouteImport.update({
  id: '/bookmarks/',
  path: '/bookmarks/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksIdRoute = BookmarksIdRouteImport.update({
  id: '/bookmarks/$id',
  path: '/bookmarks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksArchiveRoute = BookmarksArchiveRouteImport.update({
  id: '/bookmarks/archive',
  path: '/bookmarks/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksFavoritesRoute = BookmarksFavoritesRouteImport.update({
  id: '/bookmarks/favorites',
  path: '/bookmarks/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const RssIndexRoute = RssIndexRouteImport.update({
  id: '/rss/',
  path: '/rss/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const RssArticleIdRoute = RssArticleIdRouteImport.update({
  id: '/rss/article/$id',
  path: '/rss/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/explore': typeof ExploreRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bookmarks/$id': typeof BookmarksIdRoute
  '/bookmarks/archive': typeof BookmarksArchiveRoute
  '/bookmarks/favorites': typeof BookmarksFavoritesRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/rss/': typeof RssIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/rss/article/$id': typeof RssArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bookmarks/$id': typeof BookmarksIdRoute
  '/bookmarks/archive': typeof BookmarksArchiveRoute
  '/bookmarks/favorites': typeof BookmarksFavoritesRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/bookmarks': typeof BookmarksIndexRoute
  '/rss': typeof RssIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/rss/article/$id': typeof RssArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/explore': typeof ExploreRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bookmarks/$id': typeof BookmarksIdRoute
  '/bookmarks/archive': typeof BookmarksArchiveRoute
  '/bookmarks/favorites': typeof BookmarksFavoritesRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/rss/': typeof RssIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/rss/article/$id': typeof RssArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/explore'
    | '/auth/callback'
    | '/bookmarks/$id'
    | '/bookmarks/archive'
    | '/bookmarks/favorites'
    | '/settings/$section'
    | '/bookmarks/'
    | '/rss/'
    | '/settings/'
    | '/rss/article/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/auth/callback'
    | '/bookmarks/$id'
    | '/bookmarks/archive'
    | '/bookmarks/favorites'
    | '/settings/$section'
    | '/bookmarks'
    | '/rss'
    | '/settings'
    | '/rss/article/$id'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/explore'
    | '/auth/callback'
    | '/bookmarks/$id'
    | '/bookmarks/archive'
    | '/bookmarks/favorites'
    | '/settings/$section'
    | '/bookmarks/'
    | '/rss/'
    | '/settings/'
    | '/rss/article/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BookmarksIdRoute: typeof BookmarksIdRoute
  BookmarksArchiveRoute: typeof BookmarksArchiveRoute
  BookmarksFavoritesRoute: typeof BookmarksFavoritesRoute
  BookmarksIndexRoute: typeof BookmarksIndexRoute
  RssIndexRoute: typeof RssIndexRoute
  RssArticleIdRoute: typeof RssArticleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/': {
      id: '/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof BookmarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/$id': {
      id: '/bookmarks/$id'
      path: '/bookmarks/$id'
      fullPath: '/bookmarks/$id'
      preLoaderRoute: typeof BookmarksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/archive': {
      id: '/bookmarks/archive'
      path: '/bookmarks/archive'
      fullPath: '/bookmarks/archive'
      preLoaderRoute: typeof BookmarksArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/favorites': {
      id: '/bookmarks/favorites'
      path: '/bookmarks/favorites'
      fullPath: '/bookmarks/favorites'
      preLoaderRoute: typeof BookmarksFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss/': {
      id: '/rss/'
      path: '/rss'
      fullPath: '/rss/'
      preLoaderRoute: typeof RssIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/rss/article/$id': {
      id: '/rss/article/$id'
      path: '/rss/article/$id'
      fullPath: '/rss/article/$id'
      preLoaderRoute: typeof RssArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsSectionRoute: typeof SettingsSectionRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsSectionRoute: SettingsSectionRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ExploreRoute: ExploreRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BookmarksIdRoute: BookmarksIdRoute,
  BookmarksArchiveRoute: BookmarksArchiveRoute,
  BookmarksFavoritesRoute: BookmarksFavoritesRoute,
  BookmarksIndexRoute: BookmarksIndexRoute,
  RssIndexRoute: RssIndexRoute,
  RssArticleIdRoute: RssArticleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
